# Generated by Django 3.1.4 on 2021-01-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_complete', models.BooleanField(default=False)),
                ('task_created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
